name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  release:
    types: [ created ]

env:
  GO_VERSION: '1.25'
  POSTGRES_URL: postgres://postgres:postgres@localhost:5432/beam?sslmode=disable
  REDIS_ADDR: localhost:6379

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          working-directory: backend

  test:
    name: Test
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: timescale/timescaledb:latest-pg16
        env:
          POSTGRES_DB: beam
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 3s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        working-directory: backend
        run: go mod download

      - name: Run database migrations
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d beam -f backend/migrations/001_initial_schema.up.sql

      - name: Run tests
        working-directory: backend
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./backend/coverage.out
          flags: unittests
          name: codecov-umbrella

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build binaries
        working-directory: backend
        run: |
          mkdir -p bin
          go build -v -o bin/beam-api ./cmd/api
          go build -v -o bin/beam-cli ./cmd/cli

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: backend/bin/*

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: kelpejol/beam-api
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=kelpejol/beam-api:buildcache
          cache-to: type=registry,ref=kelpejol/beam-api:buildcache,mode=max

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build, docker]
    if: github.event_name == 'release'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build release binaries
        working-directory: backend
        run: |
          mkdir -p release
          
          # Linux AMD64
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o release/beam-api-linux-amd64 ./cmd/api
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o release/beam-cli-linux-amd64 ./cmd/cli
          
          # Linux ARM64
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o release/beam-api-linux-arm64 ./cmd/api
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o release/beam-cli-linux-arm64 ./cmd/cli
          
          # macOS AMD64
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o release/beam-api-darwin-amd64 ./cmd/api
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o release/beam-cli-darwin-amd64 ./cmd/cli
          
          # macOS ARM64 (Apple Silicon)
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o release/beam-api-darwin-arm64 ./cmd/api
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o release/beam-cli-darwin-arm64 ./cmd/cli
          
          # Windows AMD64
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o release/beam-api-windows-amd64.exe ./cmd/api
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o release/beam-cli-windows-amd64.exe ./cmd/cli

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: backend/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}