# docker-compose.yml for Beam
#
# Complete local development and production environment for Beam
#
# Services:
#   - PostgreSQL: Durable storage with TimescaleDB for time-series data
#   - Redis: Hot path operations (sub-millisecond balance checks)
#   - Beam API: Main gRPC + REST server
#   - pgAdmin: Database management UI (optional)
#   - Redis Commander: Redis inspection UI (optional)
#
# Usage:
#   docker-compose up -d           # Start all services
#   docker-compose logs -f beam-api  # Follow API logs
#   docker-compose down            # Stop all services
#   docker-compose down -v         # Stop and remove volumes (fresh start)

version: '3.8'

services:
  # PostgreSQL with TimescaleDB for durable storage
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: beam-postgres
    restart: unless-stopped
    
    environment:
      POSTGRES_DB: beam
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Performance tuning
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_MAX_CONNECTIONS: 100
      POSTGRES_EFFECTIVE_CACHE_SIZE: 1GB
      POSTGRES_WORK_MEM: 16MB
    
    ports:
      - "5432:5432"
    
    volumes:
      # Persist database data
      - postgres_data:/var/lib/postgresql/data
      
      # Auto-run migrations on startup
      - ./backend/migrations:/docker-entrypoint-initdb.d
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d beam"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    
    networks:
      - beam-network

  # Redis for hot path balance operations
  redis:
    image: redis:7-alpine
    container_name: beam-redis
    restart: unless-stopped
    
    command: >
      redis-server
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 60 1000
      --appendonly yes
      --appendfsync everysec
    
    ports:
      - "6379:6379"
    
    volumes:
      # Persist Redis data (RDB snapshots and AOF)
      - redis_data:/data
    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    
    networks:
      - beam-network

  # Beam API server (gRPC + REST)
  beam-api:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile
      args:
        GO_VERSION: "1.25"
    container_name: beam-api
    restart: unless-stopped
    
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    
    environment:
      # Server ports
      GRPC_PORT: "9090"
      HTTP_PORT: "8080"
      
      # Database connections
      REDIS_ADDR: "redis:6379"
      POSTGRES_URL: "postgres://postgres:postgres@postgres:5432/beam?sslmode=disable"
      
      # Application config
      LOG_LEVEL: "debug"
      ENVIRONMENT: "development"
      
      # Optional: Enable detailed metrics
      ENABLE_METRICS: "true"
      ENABLE_PROFILING: "false"
    
    ports:
      - "9090:9090"  # gRPC
      - "8080:8080"  # HTTP (REST + health checks + metrics)
    
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    
    networks:
      - beam-network
    
    # Resource limits (adjust for production)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M

  # pgAdmin for database management (optional, disable in production)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: beam-pgadmin
    restart: unless-stopped
    profiles:
      - tools  # Only start with --profile tools
    
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@beam.dev
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    
    ports:
      - "5050:80"
    
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    
    networks:
      - beam-network

  # Redis Commander for Redis inspection (optional, disable in production)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: beam-redis-commander
    restart: unless-stopped
    profiles:
      - tools  # Only start with --profile tools
    
    environment:
      REDIS_HOSTS: local:redis:6379
    
    ports:
      - "8081:8081"
    
    networks:
      - beam-network

  # Prometheus for metrics collection (optional)
  prometheus:
    image: prom/prometheus:latest
    container_name: beam-prometheus
    restart: unless-stopped
    profiles:
      - monitoring
    
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    
    ports:
      - "9091:9090"
    
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    
    networks:
      - beam-network

  # Grafana for metrics visualization (optional)
  grafana:
    image: grafana/grafana:latest
    container_name: beam-grafana
    restart: unless-stopped
    profiles:
      - monitoring
    
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    
    ports:
      - "3000:3000"
    
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana-dashboards:/etc/grafana/provisioning/dashboards
    
    networks:
      - beam-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  beam-network:
    driver: bridge

# =============================================================================
# USAGE EXAMPLES
# =============================================================================
#
# Development (minimal setup):
#   docker-compose up -d postgres redis beam-api
#
# Development with tools:
#   docker-compose --profile tools up -d
#
# Development with monitoring:
#   docker-compose --profile monitoring up -d
#
# Production:
#   docker-compose up -d postgres redis beam-api
#
# Scaling:
#   docker-compose up -d --scale beam-api=3
#
# Fresh start:
#   docker-compose down -v && docker-compose up -d
#
# View logs:
#   docker-compose logs -f beam-api
#
# Access services:
#   - Beam gRPC: localhost:9090
#   - Beam REST: http://localhost:8080
#   - PostgreSQL: localhost:5432 (user: postgres, password: postgres)
#   - Redis: localhost:6379
#   - pgAdmin: http://localhost:5050 (tools profile)
#   - Redis Commander: http://localhost:8081 (tools profile)
#   - Prometheus: http://localhost:9091 (monitoring profile)
#   - Grafana: http://localhost:3000 (monitoring profile)